# :schema https://developers.openai.com/codex/config-schema.json

[desktop.appearanceDarkChromeTheme.fonts]
code = '"Hack Nerd Font"'

[desktop.appearanceLightChromeTheme.fonts]
code = '"Hack Nerd Font"'
