# this is a list of pypi packages to install into system python for general use
pip install --upgrade ansible-toolkit
pip install --upgrade autoenv
pip install --upgrade autopep8
pip install --upgrade awscli
pip install --upgrade cdiff
pip install --upgrade cookiecutter
pip install --upgrade csvkit
pip install --upgrade gunicorn
pip install --upgrade howdoi
pip install --upgrade http-prompt
pip install --upgrade httpie
pip install --upgrade jupyter
pip install --upgrade markdown
pip install --upgrade neovim
pip install --upgrade pip
pip install --upgrade pip-tools
pip install --upgrade ptpython
pip install --upgrade pytest
pip install --upgrade pythonpy
pip install --upgrade pyyaml
pip install --upgrade saws
pip install --upgrade sshuttle
pip install --upgrade virtualenv
pip install --upgrade virtualenvwrapper
