format = """
$username$hostname \
$shlvl\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$crystal\
$custom\
$time\
$line_break\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status $cmd_duration\
$line_break\
$jobs\
$battery\
$character\
$status"""

# ---------- customizations

[aws]
symbol = "A☁️ "
format = '[\[$symbol:$profile:$region\]]($style)'
style = "bold grey"

[character]
success_symbol = "[╰➜]($style)"
error_symbol = "[╰✗](bold red)"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "fg:yellow bg:#0000ff"
format = "├─ [ $path]($style)[$read_only]($read_only_style)"

[gcloud]
symbol = "G☁️ "
format = '[\[$symbol:$account(\($project\))]($style)\]'

[git_branch]
style = "#ffff00 inverted"
format = "[ $symbol$branch]($style)"

[hostname]
ssh_only = false
style = "bg:#0000ff fg:yellow"
format = "[@$hostname]($style)"
disabled = false

[kubernetes]
format = '[\[⛵:$context\]](bold red)'
disabled = false

[package]
format = '[\[🎁:$version\]](white bold)'

[nodejs]
format = '[\[⬢:$version\]](bold green)'

[python]
python_binary = "python3"
symbol = "🐍"
format = '[\[${symbol}:${pyenv_prefix}${version}( \($virtualenv\))]($style)\]'

[username]
style_user = "bg:#0000ff fg:yellow"
style_root = "bg:#ff0000 fg:white"
format = "╭─ [$user]($style)"
disabled = false
show_always = true

[status]
style = "bg:#ff0000 fg:bold fg:white"
format = '[\[$status\]]($style) '
disabled = false

[time]
disabled = false
format = '[\[$time\]]($style)'
time_format = "%T"
